add_newline = true

# without $git_status 
format = '''$hostname$directory$git_branch$git_status$all$fill$git_commit$git_state$cmd_duration$battery
$character'''

# Can use right-format instead of fill
# right_format = '''$git_branch$git_commit$battery$cmd_duration
# $character'''

command_timeout = 5000

[os]
disabled = true
format = '[$symbol](bold white) '   

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[shell]
disabled = true
bash_indicator = ""
powershell_indicator = ""
cmd_indicator = ""

[hostname]
disabled = false
ssh_only = true 
format = "[█](fg:#E8E3E3 bg:#24263A)[$ssh_symbol$hostname](bold bg:#E8E3E3)[](fg:#E8E3E3 bg:none) "
# format = "[](fg:#24263A bg:none)[█](fg:#E8E3E3 bg:#24263A)[$ssh_symbol$hostname](bold bg:#E8E3E3)[](fg:#E8E3E3 bg:none) "

# Third param
[directory]
disabled = false
style = "fg:#E8E3E3 bg:#24263A bold"
truncation_length = 3
truncation_symbol = "~/…/"
truncate_to_repo = false
# Repo format
repo_root_format = "[ $before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
# Non repo format
format = "[](fg:#24263A bg:none)[ ](fg:#6791c9 bg:#24263a)[](fg:#24263a bg:#24263A)[$path](fg:#E8E3E3 bg:#24263a)[ ](fg:#24263a bg:none)"
read_only = " "
read_only_style = "197"
# read_only = "  "

# [directory.substitutions]
# "Documents" = " 󰈙 "
# "Downloads" = "  "

[fill]
disabled = false
symbol = '─'
style = 'cyan'

[git_branch]
disabled = false
format = "[](fg:#24263a bg:none)[  ](fg:#9ccfd8 bg:#24263a)[$branch]($style)[](fg:#24263a bg:#24263a)[](fg:#24263a bg:#24263a)[$symbol](fg:#81C19B bg:#24263a)[ ](fg:#24263a bg:none)"
style = "fg:#E8E3E3 bg:#24263a"
symbol = " "

[git_status]
disabled = false
format = "[$all_status$ahead_behind]($style) "
# format = "[](fg:#24263a bg:none)[$all_status$ahead_behind]($style)[](fg:#24263a bg:#24263a) "
style = "fg:#E8E3E3 bg:none"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# up_to_date = " 󰄸 "
# untracked = "?${count}"
# stashed = ""
# modified = "!${count}"
# staged = "+${count}"
# renamed = "»${count}"
deleted = " ${count}"

[git_commit]
disabled = false
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
disabled = false
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
disabled = false
min_time = 500
format = " [](fg:#24263a bg:none)[$duration]($style)[](fg:#24263a bg:none) |"
style = "fg:#E8E3E3 bg:#24263a bold"


[character]
disabled = false
success_symbol = "[  ](#6791c3 bold)"
error_symbol =   "[  ](#B66467 bold)"
# [character] 
# success_symbol = "[❯](green)"
# error_symbol = "[❯](red)"

[battery]
disabled = false
format = " [$symbol$percentage]($style)"
# discharging_symbol = "󰁹 "
full_symbol = "󰁹 "
charging_symbol = "󰂄 " 
discharging_symbol = "󰂃 "

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 20
style = "red"

[[battery.display]]  # "bold yellow" style when capacity is between 15% and 50%
threshold = 50
style = "yellow"

[[battery.display]]  # "green" style when capacity is between 50% and 100%
threshold = 100
style = "green"


# [time]
# disabled = false
# style = "bold bright-black"
# format = "[$time]($style)"

[sudo]
disabled = false
# symbol = "             "
symbol = ""
format = '[\($symbol\)](bold blue) '

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[memory_usage]
# symbol = " "

[nim]
# symbol = " "

[nix_shell]
symbol = " "

[package]
# symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
# format = "via [ Node.js $version](bold green) "
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
symbol = " "

# Other languages configurations:
# c.disabled = true
# cmake.disabled = true
# haskell.disabled = true
# python.disabled = true
# ruby.disabled = true
# rust.disabled = true
# perl.disabled = true
# package.disabled = true
# lua.disabled = true
# java.disabled = true
# golang.disabled = true
