#!/bin/bash

## SCRIPT TAKEN FROM https://github.com/mischavandenburg/dotfiles ##

new_daily_note() {
    # Create the directory structure if it doesn't exist
    mkdir -p "$directory"
    # Create the daily notes file
    touch "$file"

    # Format the file with the daily template
    cat <<EOF >"$file"
---
id: $timestamp
status:
tags: 
---

[[$yesterday]] - [[$tomorrow]]

## Intention

What do I want to achieve today and tomorrow?


## Tracking

- [ ] Meditation
- [ ] Strength training
- [ ] Oral routine
- [ ] Create schedule for tomorrow

Ideas for the future:
- [ ] Run
- [ ] Skin routine

## Log
EOF
}

SECOND_BRAIN=("/home/elgohr/Notes")
today=$(date +"%Y-%m-%d")
tomorrow=$(gdate -d "tomorrow" '+%Y-%m-%d')
yesterday=$(gdate -d "yesterday" '+%Y-%m-%d')
directory="$SECOND_BRAIN/periodic-notes/daily-notes"
file="$directory/$(date +"%Y-%m-%d").md"
# create unique identifier and links section
timestamp="$(date +"%Y%m%d%H%m")"

cd "$SECOND_BRAIN" || exit

# If the daily note does not exist, create a new one.
# This uses the test command with the -f flag.
if [ ! -f "$file" ]; then
    echo "File does not exist, creating a new daily note."
    new_daily_note
fi

# Open the daily note at the bottom of the file in insert mode and run NoNeckPain to make it center
nvim '+ normal zzo' "$file"
# nvim '+ normal Gzzo' "$file" -c :NoNeckPain
