#!/bin/bash

# Replace this with the correct path to your Firefox executable
firefox_exe="/System/Volumes/Data/Applications/Firefox Developer Edition.app"


# Construct the search query URL
query="$*"
encoded_query=$(python3 -c "import urllib.parse; print(urllib.parse.quote('$query'))")
search_url="https://www.google.com/search?q=$encoded_query"

# Execute the Firefox command
open "$firefox_exe" --args -new-window "$search_url"
